# Generated by Django 4.1.5 on 2023-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectfourgame',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='connectfourgame',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='connectfourgame',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectfourgame',
            name='vs_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connectfourgame',
            name='current_player',
            field=models.CharField(default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='connectfourgame',
            name='winner',
            field=models.CharField(blank=True, default=1, max_length=1),
            preserve_default=False,
        ),
    ]
