# Generated by Django 4.1.5 on 2023-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0007_rename_next_player_connectfourgame_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectfourgame',
            name='board',
            field=models.CharField(default=[[' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' ']], max_length=42),
        ),
    ]
