# Generated by Django 4.1.5 on 2023-01-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0008_connectfourgame_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectfourgame',
            name='board',
        ),
    ]
