# Generated by Django 4.1.5 on 2023-01-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0009_remove_connectfourgame_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectfourgame',
            name='board',
            field=models.CharField(default='                                          ', max_length=42),
        ),
    ]
